---
- name: Install Docker
  apt:
    name: docker.io
    state: latest

- name: Load Docker Image
  docker_image:
    name: "minecraft_server"
    source: load
    load_path: "D:\\Computer_Science\\CS_312_System_administration\\minecraft-docker-images\\minecraft_server.tar"

- name: Run Minecraft Docker Container
  docker_container:
    name: minecraft_server
    image: minecraft_server
    state: started
    ports:
      - "25565:25565"
    restart_policy: always
