---
- hosts: minecraft_servers  # The group of hosts as defined in your Ansible hosts file
  become: true  # Assumes superuser privileges
  tasks:
    - name: Transfer Docker image tarball to EC2
      copy:
        src: "/home/konnichiwa/Desktop/minecraft_server.tar"
        dest: "/home/konnichiwa/Desktop/minecraft_server.tar"
    
    - name: Transfer SSH key to EC2
      copy:
        src: "/home/konnichiwa/Desktop/mykeypair.pem"
        dest: "/home/konnichiwa/Desktop/mykeypair.pem"
        mode: '0400'  # Ensures the key file is not publicly readable